### https://github.com/realm/SwiftLint/blob/master/README_CN.md
### https://realm.github.io/SwiftLint/rule-directory.html
disabled_rules: # 执行时排除掉的规则
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - empty_count
  - private_over_fileprivate
  - trailing_newline
  - vertical_whitespace
  - force_cast
opt_in_rules: # 一些规则仅仅是可选的
  - missing_docs
  # 可以通过执行如下指令来查找所有可用的规则:
  # swiftlint rules
#included: # 执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略。
#  - Source
excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - QHProjectDemo/Vendors/FitSize/SwiftyFitsize.swift
  - QHProjectDemoTests
  - QHProjectDemoUITests

# 可配置的规则可以通过这个配置文件来自定义
# 二进制规则可以设置他们的严格程度
force_cast: warning # 隐式
force_try:
  severity: warning # 显式
# 同时有警告和错误等级的规则，可以只设置它的警告等级
# 隐式
line_length: 120
function_body_length: 50
function_parameter_count: 5
trailing_newline: disabled
# 可以通过一个数组同时进行隐式设置
type_body_length:
  - 300 # warning
  - 400 # error
# 或者也可以同时进行显式设置
file_length:
  warning: 600
  error: 1000
# 命名规则可以设置最小长度和最大程度的警告/错误
# 此外它们也可以设置排除在外的名字
type_name:
  min_length: 4 # 只是警告
  max_length: # 警告和错误
    warning: 40
    error: 50
  excluded: iPhone # 排除某个名字
identifier_name:
  excluded: # 排除某些名字
    - id
    - URL
    - GlobalAPIKey
    - vc
    - VC
    - y
    - x
    - Router
    - i
reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle)
